import type { Config } from 'tailwindcss'
import tokens from './design-tokens/theme.json'

export default {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Premium Textile Palette
        primary: {
          DEFAULT: tokens.colors.primary.base,
          light: tokens.colors.primary.light,
          dark: tokens.colors.primary.dark,
        },
        accent: {
          saffron: tokens.colors.accent.saffron,
          terracotta: tokens.colors.accent.terracotta,
          sage: tokens.colors.accent.sage,
          indigo: tokens.colors.accent.indigo,
        },
        surface: {
          base: tokens.colors.surface.base,
          elevated: tokens.colors.surface.elevated,
          card: tokens.colors.surface.card,
          hover: tokens.colors.surface.cardHover,
          overlay: tokens.colors.surface.overlay,
        },
        border: {
          base: tokens.colors.border.base,
          muted: tokens.colors.border.muted,
          accent: tokens.colors.border.accent,
        },
        text: {
          primary: tokens.colors.text.primary,
          secondary: tokens.colors.text.secondary,
          muted: tokens.colors.text.muted,
          accent: tokens.colors.text.accent,
        },
        semantic: {
          success: tokens.colors.semantic.success,
          warning: tokens.colors.semantic.warning,
          error: tokens.colors.semantic.error,
          info: tokens.colors.semantic.info,
        },
        // Legacy compatibility
        navy: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#A0A4B8',
          400: '#6B7089',
          500: '#4A4E63',
          600: '#33374A',
          700: '#222838',
          800: '#1A1F2E',
          900: '#131823',
          950: '#0A0E17',
        },
        gold: {
          DEFAULT: tokens.colors.accent.saffron,
          50: '#FEF7ED',
          100: '#FDEFD4',
          200: '#FBD9A8',
          300: '#F8C171',
          400: '#F5A03F',
          500: tokens.colors.accent.saffron,
          600: '#D88D2E',
          700: '#B36E23',
          800: '#8F5723',
          900: '#744820',
          metallic: tokens.colors.accent.saffron,
        },
      },
      fontFamily: {
        heading: tokens.typography.fontFamily.heading.split(',').map(f => f.trim()),
        sans: tokens.typography.fontFamily.body.split(',').map(f => f.trim()),
        body: tokens.typography.fontFamily.body.split(',').map(f => f.trim()),
        mono: tokens.typography.fontFamily.mono.split(',').map(f => f.trim()),
      },
      fontSize: {
        xs: [tokens.typography.fontSize.xs, { lineHeight: tokens.typography.lineHeight.normal }],
        sm: [tokens.typography.fontSize.sm, { lineHeight: tokens.typography.lineHeight.normal }],
        base: [tokens.typography.fontSize.base, { lineHeight: tokens.typography.lineHeight.normal }],
        lg: [tokens.typography.fontSize.lg, { lineHeight: tokens.typography.lineHeight.normal }],
        xl: [tokens.typography.fontSize.xl, { lineHeight: tokens.typography.lineHeight.tight }],
        '2xl': [tokens.typography.fontSize['2xl'], { lineHeight: tokens.typography.lineHeight.tight }],
        '3xl': [tokens.typography.fontSize['3xl'], { lineHeight: tokens.typography.lineHeight.tight }],
        '4xl': [tokens.typography.fontSize['4xl'], { lineHeight: tokens.typography.lineHeight.tight }],
        '5xl': [tokens.typography.fontSize['5xl'], { lineHeight: tokens.typography.lineHeight.tight }],
      },
      letterSpacing: {
        tight: tokens.typography.letterSpacing.tight,
        normal: tokens.typography.letterSpacing.normal,
        wide: tokens.typography.letterSpacing.wide,
        wider: tokens.typography.letterSpacing.wider,
      },
      borderRadius: {
        sm: tokens.borderRadius.sm,
        DEFAULT: tokens.borderRadius.md,
        md: tokens.borderRadius.md,
        lg: tokens.borderRadius.lg,
        xl: tokens.borderRadius.xl,
        '2xl': tokens.borderRadius['2xl'],
        full: tokens.borderRadius.full,
      },
      boxShadow: {
        sm: tokens.shadows.sm,
        DEFAULT: tokens.shadows.md,
        md: tokens.shadows.md,
        lg: tokens.shadows.lg,
        xl: tokens.shadows.xl,
        'glow-indigo': tokens.shadows.glow.indigo,
        'glow-saffron': tokens.shadows.glow.saffron,
        'glow-terracotta': tokens.shadows.glow.terracotta,
        inner: tokens.shadows.inner,
        // Legacy
        premium: tokens.shadows.sm,
        'premium-lg': tokens.shadows.md,
        gold: tokens.shadows.glow.saffron,
        'gold-lg': tokens.shadows.glow.saffron,
        navy: tokens.shadows.md,
        'navy-lg': tokens.shadows.lg,
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(circle at center, var(--tw-gradient-stops))',
        'gradient-premium': `linear-gradient(135deg, ${tokens.colors.surface.elevated} 0%, ${tokens.colors.surface.card} 100%)`,
        'gradient-luxury': `linear-gradient(160deg, ${tokens.colors.surface.card} 0%, ${tokens.colors.surface.elevated} 50%, ${tokens.colors.surface.base} 100%)`,
        'gradient-saffron': `linear-gradient(135deg, ${tokens.colors.accent.saffron} 0%, #D88D2E 100%)`,
        'gradient-indigo': `linear-gradient(135deg, ${tokens.colors.accent.indigo} 0%, ${tokens.colors.primary.dark} 100%)`,
        'gradient-mesh': 'radial-gradient(at 0% 0%, rgba(74, 95, 209, 0.15) 0%, transparent 50%), radial-gradient(at 100% 100%, rgba(232, 168, 70, 0.1) 0%, transparent 50%)',
      },
      transitionTimingFunction: {
        smooth: `cubic-bezier(${tokens.motion.ease.smooth.join(',')})`,
        spring: `cubic-bezier(${tokens.motion.ease.spring.join(',')})`,
        fabric: `cubic-bezier(${tokens.motion.ease.fabric.join(',')})`,
      },
      transitionDuration: {
        instant: `${tokens.motion.duration.instant}ms`,
        fast: `${tokens.motion.duration.fast}ms`,
        base: `${tokens.motion.duration.base}ms`,
        slow: `${tokens.motion.duration.slow}ms`,
        slower: `${tokens.motion.duration.slower}ms`,
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-smooth forwards',
        'fade-up': 'fadeUp 0.4s ease-smooth forwards',
        'slide-in': 'slideIn 0.3s ease-spring forwards',
        'shimmer': 'shimmer 2s linear infinite',
        'float': 'float 3s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'pulse-subtle': 'pulseSubtle 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideIn: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        glow: {
          '0%': { boxShadow: `0 0 8px ${tokens.colors.primary.glow}` },
          '100%': { boxShadow: `0 0 24px ${tokens.colors.primary.glow}, 0 0 32px ${tokens.colors.primary.glow}` },
        },
        pulseSubtle: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.85' },
        },
      },
    },
  },
  plugins: [],
} satisfies Config
